dist: trusty
sudo: required
language: node_js

addons:
  sonarqube: true
  
jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false